# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=26.3
loader_version=0.19.5
loom_version=1.18.2
# Mod Properties
mod_version=0.7.3
maven_group=github.amvern
archives_base_name=twodimensionalreloaded
# Dependencies
# check this on https://modmuss50.me/fabric.html
fabric_version=0.161.0+26.3
iris_version=1.11.6+26.3-fabric
sodium_version=0.9.2+mc26.3